apiVersion: v1
kind: Secret
metadata:
  name: secreto1
# kubernetes.io/service-account-token | kubernetes.io/dockercfg | kubernetes.io/dockerconfigjson
# kubernetes.io/basic-auth | kubernetes.io/ssh-auth | kubernetes.io/tls | bootstrap.kubernetes.io/token
# https://kubernetes.io/docs/concepts/configuration/secret/  
type: Opaque 
data:
  MYSQL_URL: amRiYzpteXNxbDovL215c3FsLTAubXlzcWwvcGV0Y2xpbmlj
  MYSQL_USER: cGV0Y2xpbmlj
  MYSQL_PASS: cGV0Y2xpbmlj
