version: '3'
services:

  mysql:
    image: carlos89/mysql-server:v1
    ports:
      - 3306:3306

  api-petclinic:
    image: carlos89/app-petclinic-curso-k8s:v1
    environment:
      MYSQL_URL: jdbc:mysql://mysql_server/petclinic
    ports:
      - 8080:8080
    links:
    - mysql:mysql_server
    depends_on:
      - mysql
