apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: name1
  labels:
    app: ubuntu
spec:
  containers:
   - name: ubuntu
     image: ubuntu
     command: ["/bin/sleep", "3650d"]
     imagePullPolicy: IfNotPresent
